codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  threshold: 30

  status:
    project:
      default: false
      tests:
        target: 100%
        paths: "tests/"
      quipucordsctl:
        target: 70%
        paths: "quipucordsctl/"
